"""added new weight

Revision ID: decd83f7d6dc
Revises: 
Create Date: 2019-01-12 13:03:47.417350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decd83f7d6dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_data', sa.Column('new_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weight_data', 'new_weight')
    # ### end Alembic commands ###
